### ISSUE TITLE
MD5校验值对不上

### ISSUE THREAD

**Issue by xuxuedong** [raddyfiy/caidao-official-version#2]
经检测，caidao-20141213.zip和caidao-20160622.zip的MD5校验值对不上  

![2020-04-16 13-45-28 的屏幕截图](https://user-images.githubusercontent.com/9376976/79419044-98bec200-7fe8-11ea-9fd2-4e40cc5288c4.png)

**Comment by raddyfiy** [comment]
> 经检测，caidao-20141213.zip和caidao-20160622.zip的MD5校验值对不上
> 
> ![2020-04-16 13-45-28 的屏幕截图](https://user-images.githubusercontent.com/9376976/79419044-98bec200-7fe8-11ea-9fd2-4e40cc5288c4.png)

MD5是exe主程序的，不是压缩包的

**Comment by xuxuedong** [comment]
尴尬了：），感谢大佬的回复
经检测，MD5值能对上
![0](https://user-images.githubusercontent.com/9376976/79526714-76847d00-8098-11ea-827b-66c577b03992.png)
